version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: mi_juego_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U usuario -d mi_juego_db -h localhost"]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 10s

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: mi_juego_db
    networks:
      - app-network

  frontend:
    build: ./frontend
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    networks:
      - app-network

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local